### ISSUE TITLE
Why does the package is not in the AUR anymore

### ISSUE THREAD

**Issue by Yasso9** [donovanglover/hyprnome#24]
When I ran `yay -Syu` it gives me this message :

 -> Packages not in AUR: hyprnome
 
 I think for a lot of persons (including me) it is easier to install a package via an AUR helper instead of compiling myself.

**Comment by Yasso9** [comment]
Ok I see … It's weird because I first installed it with yay so someone else must have added it but removed it later.
But yeah I would be absolutely for it being added to the AUR, it's a pretty good program !

**Comment by donovanglover** [comment]
Closing since hyprnome is now available in the AUR (Thanks @Fhraze!)
