### ISSUE TITLE
Add flag for cycling through workspaces

### ISSUE THREAD

**Issue by dit7ya** [donovanglover/hyprnome#40]
# Feature Request

## Summary

Can we have a flag like `--cycle` for cycling through all open workspaces?

I would like to simply assign `SUPER+TAB` to cycle between all open workspaces - which means after workspace 9, switching to workspace 0 (assuming those workspaces are open) and continuing again.

## Motivation
Having only one keybind for cycling to all windows ad infinitum. (And perhaps another keybind for the reverse direction).

## Priorities
Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/donovanglover/hyprnome/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by donovanglover** [comment]
Done in https://github.com/donovanglover/hyprnome/pull/43
