### ISSUE TITLE
v0.3.0

### ISSUE THREAD

**Issue by donovanglover** [donovanglover/hyprnome#45]
Will make a new release after testing with [Hyprland v0.34.0](https://github.com/hyprwm/Hyprland/releases/tag/v0.34.0).

**Comment by kensad-ops** [comment]
Hello. I just want to know when will v0.3.0 is ready tobe release ? hyprnome apparently not working with hyprland 0.40.0 at the moment.

**Comment by donovanglover** [comment]
Thanks for the nudge. Will make a release today.

Apologies for not getting to this sooner!

**Comment by donovanglover** [comment]
Done in https://github.com/donovanglover/hyprnome/commit/e0c1a11dc0e90bc490573a53cc4cbe1fb6046fdf
