### ISSUE TITLE
Hyprnome not running via exec bind

### ISSUE THREAD

**Issue by wyqydsyq** [donovanglover/hyprnome#92]
# Bug Report

## Environment

- Output of `uname -a`: 6.9.7-1-default
- Output of `hyprnome -V`: 0.3.0
- Output of `hyprctl version`: 0.41.2

## Expected Behavior
Running Hyprnome via Hyprland exec binding works

## Current Behavior
`bind=SUPER_SHIFT,Q,exec,hyprnome` should run hypernome on pressing super+shift+Q but nothing happens

Running `hyprnome` directly in my terminal works perfectly and switches workspaces as expected

Running anything else with the exact same binding e.g. `bind=SUPER_SHIFT,Q,exec,firefox` works perfectly

But for some reason hyprnome does nothing when I run it from an exec binding

## Step to Reproduce
 - Install on OpenSUSE TumbleWeed w/ latest hyprland and hyprnome installed via Cargo
 - Try configuring hyprnome to execute in a hyprland binding

## Priorities
Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/donovanglover/hyprnome/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by donovanglover** [comment]
Sounds like hyprnome isn't available in the `$PATH` that `hyprland.conf` has access to. [This thread](https://forums.opensuse.org/t/help-with-adding-to-path/150549) covers some ways you can add `hyprnome` to your `$PATH`.

**Comment by donovanglover** [comment]
Closing since not a hyprnome issue

**Comment by wyqydsyq** [comment]
It's installed to `~/.cargo/bin` which is in my `$PATH` and the reason I can run it normally through a terminal, so I don't think that is the issue here
