### ISSUE TITLE
Not working on hyprland 0.42.0

### ISSUE THREAD

**Issue by xlsft** [donovanglover/hyprnome#95]
# Bug Report

## Environment
```
Linux xl 6.10.3-zen1-2-zen #1 ZEN SMP PREEMPT_DYNAMIC Tue, 06 Aug 2024 07:47:21 +0000 x86_64 GNU/Linux
```
```
hyprnome 0.3.0
```
```
Hyprland, built from branch main at commit 9a09eac79b85c846e3a865a9078a3f8ff65a9259  (props: bump version to 0.42.0).
Date: Wed Aug 7 22:17:10 2024
Tag: v0.42.0, commits: 5069

flags: (if any)
```

## Expected Behavior
It should work)

## Current Behavior
It don;t, every action result
```
Failed to dispatch ID ***
```

## Step to Reproduce
Update to 0.42.0 hyprland

## Priorities
Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/donovanglover/hyprnome/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by xlsft** [comment]
just confirmed
working fine on 0.41.2
```
Hyprland, built from branch  at commit 918d8340afd652b011b937d29d5eea0be08467f5  (flake.lock: update).
Date: Tue Jun 25 12:06:02 2024
Tag: v0.41.2, commits: 4886

flags: (if any)
```

**Comment by donovanglover** [comment]
Fixed in `master`. Should make a new release soon.

**Comment by donovanglover** [comment]
Done in https://github.com/donovanglover/hyprnome/releases/tag/0.3.1
